# Generated by Django 4.0.2 on 2022-04-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_orders_orderupdate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
